/*
 * Management dashboard HTML — auto-included by web_api.c.
 * Extracted from ota.c for maintainability.
 */
#pragma once

static const char MGMT_HTML[] =
"<!DOCTYPE html><html><head><meta charset=utf-8>"
"<meta name=viewport content='width=device-width,initial-scale=1'>"
"<title>Shelly Management</title>"
"<style>"
"*{box-sizing:border-box}body{font-family:sans-serif;max-width:560px;margin:0 auto;padding:1em}"
"h2{margin-bottom:.3em}"
".tabs{display:flex;border-bottom:2px solid #0066cc;margin:1em 0 0}"
".tab{padding:.6em 1.2em;cursor:pointer;border:1px solid #ccc;border-bottom:none;"
"  margin-right:2px;border-radius:6px 6px 0 0;background:#f5f5f5;font-size:.95em}"
".tab.act{background:#0066cc;color:#fff;border-color:#0066cc}"
".pane{display:none;padding:1em 0}.pane.act{display:block}"
"input,select{padding:.5em;margin:.3em 0 .8em;border:1px solid #ccc;border-radius:3px}"
"label{font-weight:bold;display:block;margin-top:.3em}"
".btn{padding:.55em 1.2em;color:#fff;border:0;cursor:pointer;font-size:.95em;border-radius:3px;margin:.3em .3em .3em 0}"
".btn-blue{background:#0066cc}.btn-green{background:#28a745}"
".btn-red{background:#dc3545}.btn-gray{background:#6c757d}"
".btn:disabled{background:#999;cursor:default}"
"#bar-wrap{display:none;margin:.8em 0;background:#eee;border-radius:4px;height:22px}"
"#bar{height:22px;background:#0066cc;border-radius:4px;width:0;transition:width .2s}"
"#bar-lbl{text-align:center;margin-top:.2em;font-size:.9em}"
".msg{font-weight:bold;margin-top:.6em}.ok{color:green}.err{color:red}"
"table{border-collapse:collapse;width:100%;margin:.5em 0}"
"td,th{border:1px solid #ddd;padding:6px 10px;text-align:left}"
"th{background:#f0f0f0}.hw-val{font-family:monospace;font-size:1.1em}"
"h4{margin:1.2em 0 .3em;color:#333;border-bottom:1px solid #ddd;padding-bottom:.2em}"
".info{font-size:.85em;color:#555;margin-bottom:.8em}"
"</style></head><body>"

"<h2 id=page-title>Shelly1Gen4 Management</h2>"
"<div id=fw-ver style='font-size:.85em;color:#666;margin-bottom:.5em'></div>"

/* ── Tab bar ── */
"<div class=tabs>"
"<div class='tab act' onclick=showTab(0)>WiFi &amp; OTA</div>"
"<div class=tab onclick=showTab(1)>Hardware</div>"
"<div class=tab onclick=showTab(2)>Scripts</div>"
"<div class=tab onclick=showTab(3)>Backup</div>"
"</div>"

/* ── Tab 0: WiFi & OTA ── */
"<div class='pane act' id=p0>"
"<h3>WiFi Settings</h3>"
"<p class=info>Credentials are stored in flash. On next OTA boot the device "
"connects to your WiFi automatically.</p>"
"<label>Hostname</label><input id=hostname placeholder='shelly-XXXXXX' maxlength=31>"
"<label>WiFi SSID</label><input id=ssid>"
"<label>WiFi Password</label><input id=pass type=password>"
"<label>Firmware URL (optional)</label>"
"<input id=url placeholder='http://server/shelly1gen4.bin'>"
"<div style='margin:1em 0'>"
"<button class='btn btn-green' onclick=doSaveRestart()>Save &amp; Restart</button>"
"<button class='btn btn-gray' onclick=doRestartThread()>Restart to Thread mode</button>"
"<button class='btn btn-blue' onclick=doRestartWifi()>Restart to WiFi mode</button>"
"<button class='btn btn-blue' onclick=doCommission()>Commission Mode</button>"
"<button class='btn btn-red' onclick=doFactory()>Factory Reset</button>"
"</div>"
"<div id=wifi-msg class=msg></div>"

"<h3>Upload Firmware</h3>"
"<label for=binfile>Select .bin file</label>"
"<input type=file id=binfile accept='.bin'>"
"<button class='btn btn-blue' id=flashbtn onclick=doUpload()>Flash Firmware</button>"
"<div id=bar-wrap><div id=bar></div></div>"
"<div id=bar-lbl></div>"
"<div id=flash-msg class=msg></div>"
"</div>"

/* ── Tab 1: Hardware ── */
"<div class=pane id=p1>"
"<h3>Hardware Status</h3>"
"<p class=info>Live readings (auto-refresh every 5 s). "
"<button class='btn btn-blue' onclick=loadHW()>Refresh now</button></p>"

"<h4>Device Type</h4>"
"<p class=info>Select the Shelly model this firmware runs on. This sets the "
"relay/switch/button/LED GPIOs and enables the power meter on the 1PM. "
"<b>Warning:</b> choosing the wrong model drives the wrong GPIOs. Saving "
"reboots the device. Matter re-commissioning is <b>not</b> required.</p>"
"<label>Model</label>"
"<select id=hw-type></select>"
"<div style='margin:.6em 0'>"
"<button class='btn btn-blue' onclick=saveHWType()>Save &amp; reboot</button>"
"</div>"
"<div id=hwtype-msg class=msg></div>"

"<h4>System</h4>"
"<table><tr><th style='width:45%'>Item</th><th>Value</th></tr>"
"<tr><td>Firmware</td><td class=hw-val id=hw-fw>-</td></tr>"
"<tr><td>Active device type</td><td class=hw-val id=hw-dev>-</td></tr>"
"<tr><td>Chip</td><td class=hw-val id=hw-chip>-</td></tr>"
"<tr><td>MAC address</td><td class=hw-val id=hw-mac>-</td></tr>"
"<tr><td>WiFi mode</td><td class=hw-val id=hw-wifi>-</td></tr>"
"<tr><td>WiFi RSSI</td><td class=hw-val id=hw-rssi>-</td></tr>"
"<tr><td>Uptime</td><td class=hw-val id=hw-up>-</td></tr>"
"<tr><td>Free heap</td><td class=hw-val id=hw-heap>-</td></tr>"
"<tr><td>Chip temperature</td><td class=hw-val id=hw-ctemp>-</td></tr>"
"<tr><td>Reset reason</td><td class=hw-val id=hw-rst>-</td></tr>"
"<tr><td>Bench mode<br><span style='font-size:.8em;color:#666'>"
"ON = GPIO10 pull-up, sensor tasks skipped (UART0 stays active).<br>"
"OFF = production (230V optocoupler, DS18B20 + occupancy running).</span></td>"
"<td class=hw-val id=hw-bench>-<br>"
"<button class='btn btn-gray' id=bench-btn onclick=toggleBench() style='margin-top:.4em'>Toggle</button>"
"</td></tr>"

"</table>"

"<h4>Inputs</h4>"
"<table><tr><th style='width:45%'>Input</th><th>Value</th></tr>"
"<tr><td>Wall switch</td><td class=hw-val id=hw-btn>-</td></tr>"
"<tr><td>Wall switch 2 (2PM)</td><td class=hw-val id=hw-btn2>-</td></tr>"
"<tr><td>PCB button</td><td class=hw-val id=hw-pcb>-</td></tr>"
"<tr><td>Digital IN (Add-on)</td><td class=hw-val id=hw-dig>-</td></tr>"
"<tr><td>Analog IN (Add-on)</td><td class=hw-val id=hw-ana>-</td></tr>"
"</table>"

"<h4>Outputs</h4>"
"<table><tr><th style='width:45%'>Output</th><th>Value</th></tr>"
"<tr><td>Relay</td><td class=hw-val id=hw-relay>-</td></tr>"
"</table>"

"<h4>Sensors</h4>"
"<table><tr><th style='width:45%'>Sensor</th><th>Value</th></tr>"
"<tr><td>Temperature (DS18B20)</td><td class=hw-val id=hw-temp>-</td></tr>"
"<tr><td>Power meter</td><td class=hw-val id=hw-power>-</td></tr>"
"</table>"
"<div id=hw-msg class=msg></div>"
"</div>"

/* ── Tab 2: Scripts ── */
"<div class=pane id=p2>"
"<h3>Endpoint Scripts</h3>"
"<p class=info>Configure Matter endpoints via Lua scripts. Each slot is one endpoint. "
"Changes require a reboot to recreate endpoints.</p>"

"<label>Slot</label>"
"<select id=sc-slot onchange=loadSlot()>"
"<option value=0>Slot 0</option><option value=1>Slot 1</option>"
"<option value=2>Slot 2</option><option value=3>Slot 3</option>"
"<option value=4>Slot 4</option><option value=5>Slot 5</option>"
"<option value=6>Slot 6</option><option value=7>Slot 7</option>"
"</select>"

"<label>Name</label><input id=sc-name placeholder='e.g. Pushbutton Toggle'>"

"<label>Endpoint Type</label>"
"<select id=sc-type>"
"<option value=0>None (disabled)</option>"
"<option value=1>OnOff Toggle + Dim + Color (client)</option>"
"<option value=2>OnOff State-Follow (client)</option>"
"<option value=4>Occupancy Sensor</option>"
"<option value=5>Illuminance Sensor</option>"
"<option value=6>Temperature Sensor</option>"
"<option value=7>Relay (OnOff Light server)</option>"
"<option value=8>Relay 2 (OnOff Light server, 2PM)</option>"
"<option value=9>Contact Sensor (BooleanState server)</option>"
"<option value=10>Electrical Power Measurement (server)</option>"
"</select>"

"<label>Trigger</label>"
"<select id=sc-trig>"
"<option value=0>Periodic</option>"
"<option value=1>On input change</option>"
"<option value=2>On button event</option>"
"</select>"

"<label>Period (ms, for periodic trigger)</label>"
"<input id=sc-period type=number value=500 min=50 max=60000>"

"<label>Lua Script</label>"
"<textarea id=sc-code style='width:100%;height:200px;font-family:monospace;font-size:.9em;"
"  tab-size:2;white-space:pre;border:1px solid #ccc;border-radius:3px;padding:.5em'"
"  placeholder='-- Write your Lua script here&#10;function run()&#10;  local evt = input.button_event()&#10;  if evt == \"short_press\" then&#10;    endpoint.command(\"toggle\")&#10;  end&#10;end'></textarea>"

"<div style='margin:1em 0'>"
"<button class='btn btn-green' onclick=saveSlot()>Save Slot</button>"
"<button class='btn btn-red' onclick=clearSlot()>Clear Slot</button>"
"<button class='btn btn-gray' onclick=loadSlot()>Reload</button>"
"</div>"
"<div id=sc-msg class=msg></div>"
"<hr style='margin:1.5em 0'>"
"<button class='btn btn-red' onclick=doScriptReboot()>Reboot Device</button>"
"<p class=info>Reboot to apply endpoint type changes.</p>"
"</div>"

/* ── Tab 3: Backup / Restore ── */
"<div class=pane id=p3>"
"<h3>Backup &amp; Restore</h3>"
"<p class=info>Download all saved settings as a backup file, or restore "
"from a previously saved backup.</p>"
"<div style='margin:.8em 0'>"
"<label style='font-weight:normal;cursor:pointer'>"
"<input type=checkbox id=bk-nvs style='margin-right:.4em;vertical-align:middle'>"
"Include NVS (Matter commissioning data)</label></div>"
"<button class='btn btn-blue' onclick=doBackup()>Download Backup</button>"
"<h3>Restore from file</h3>"
"<input type=file id=restfile accept='.json'>"
"<button class='btn btn-green' onclick=doRestore()>Restore Backup</button>"
"<div id=bk-msg class=msg></div>"
"</div>"

"<script>"
/* Tab switching */
"function showTab(n){"
"  document.querySelectorAll('.tab').forEach(function(t,i){t.className=i==n?'tab act':'tab'});"
"  document.querySelectorAll('.pane').forEach(function(p,i){p.className=i==n?'pane act':'pane'});"
"  if(n==1){loadHWConfig();loadHW();startHWTimer()}else{stopHWTimer()}"
"  if(n==2){loadSlot()}"
"}"

/* Load saved settings + firmware version on page load */
"function loadSettings(){"
"  var x=new XMLHttpRequest();"
"  x.onload=function(){"
"    if(x.status==200){"
"      var d=JSON.parse(x.responseText);"
"      document.getElementById('hostname').value=d.hostname||'';"
"      document.getElementById('ssid').value=d.ssid||'';"
"      document.getElementById('pass').value=d.pass||'';"
"      document.getElementById('url').value=d.url||'';"
"      if(d.version){document.getElementById('fw-ver').textContent='Firmware: '+d.version}"
"      if(d.hostname){document.getElementById('page-title').textContent=d.hostname+' Management';document.title=d.hostname+' Management'}"
"    }"
"  };"
"  x.open('GET','/api/settings');x.send();"
"}"
"loadSettings();"

/* WiFi save & restart */
"function doSaveRestart(){"
"  var b='hostname='+encodeURIComponent(document.getElementById('hostname').value)"
"    +'&ssid='+encodeURIComponent(document.getElementById('ssid').value)"
"    +'&pass='+encodeURIComponent(document.getElementById('pass').value)"
"    +'&url='+encodeURIComponent(document.getElementById('url').value);"
"  var x=new XMLHttpRequest();"
"  x.onload=function(){document.getElementById('wifi-msg').innerHTML="
"    '<span class=ok>Saved! Restarting...</span>'};"
"  x.onerror=function(){document.getElementById('wifi-msg').innerHTML="
"    '<span class=ok>Saved! Restarting...</span>'};"
"  x.open('POST','/ota');x.setRequestHeader('Content-Type','application/x-www-form-urlencoded');"
"  x.send(b);"
"}"

/* Restart to Thread mode (normal boot: Matter over Thread) */
"function doRestartThread(){"
"  if(!confirm('Restart into Thread mode? The device reboots and runs Matter over Thread.'))return;"
"  var x=new XMLHttpRequest();"
"  x.onload=function(){document.getElementById('wifi-msg').innerHTML="
"    '<span class=ok>Restarting into Thread mode...</span>'};"
"  x.open('POST','/api/restart');x.send();"
"}"

/* Restart to WiFi mode (WiFi + dashboard for 10 min, then back to Thread) */
"function doRestartWifi(){"
"  if(!confirm('Restart into WiFi mode? The device joins WiFi for management and falls back to Thread after 10 minutes.'))return;"
"  var x=new XMLHttpRequest();"
"  x.onload=function(){document.getElementById('wifi-msg').innerHTML="
"    '<span class=ok>Restarting into WiFi mode (10 min, then back to Thread)...</span>'};"
"  x.open('POST','/api/wifi-mode');x.send();"
"}"

/* Commission mode */
"function doCommission(){"
"  if(!confirm('Commission Mode: removes all Matter pairings and reboots into BLE pairing mode. WiFi and script settings are kept. Continue?'))return;"
"  var x=new XMLHttpRequest();"
"  x.onload=function(){document.getElementById('wifi-msg').innerHTML="
"    '<span class=ok>Rebooting into commission mode...</span>'};"
"  x.open('POST','/api/commission');x.send();"
"}"

/* Factory reset */
"function doFactory(){"
"  if(!confirm('WARNING: This erases ALL settings and Matter pairing data. Continue?'))return;"
"  if(!confirm('Are you really sure? This cannot be undone!'))return;"
"  var x=new XMLHttpRequest();"
"  x.onload=function(){document.getElementById('wifi-msg').innerHTML="
"    '<span class=ok>Factory reset done. Restarting...</span>'};"
"  x.open('POST','/api/factory-reset');x.send();"
"}"

/* Firmware upload */
"function doUpload(){"
"  var f=document.getElementById('binfile').files[0];"
"  if(!f){alert('Select a .bin file first');return;}"
"  var btn=document.getElementById('flashbtn');"
"  var wrap=document.getElementById('bar-wrap');"
"  var bar=document.getElementById('bar');"
"  var lbl=document.getElementById('bar-lbl');"
"  var st=document.getElementById('flash-msg');"
"  btn.disabled=true;wrap.style.display='block';st.textContent='';st.className='msg';"
"  var xhr=new XMLHttpRequest();"
"  xhr.upload.onprogress=function(e){"
"    if(e.lengthComputable){"
"      var pct=Math.round(e.loaded/e.total*100);"
"      bar.style.width=pct+'%';"
"      lbl.textContent='Uploading: '+pct+'% ('+Math.round(e.loaded/1024)+'/'+"
"        Math.round(e.total/1024)+' KB)';"
"    }"
"  };"
"  xhr.onload=function(){"
"    if(xhr.status===200){"
"      bar.style.width='100%';"
"      lbl.textContent='Upload complete';"
"      st.innerHTML='<span class=ok>Flashed! Restarting...</span>';"
"    }else{"
"      st.innerHTML='<span class=err>Error: '+xhr.responseText+'</span>';"
"      btn.disabled=false;"
"    }"
"  };"
"  xhr.onerror=function(){"
"    st.innerHTML='<span class=err>Connection lost</span>';btn.disabled=false;};"
"  xhr.open('POST','/upload');"
"  xhr.setRequestHeader('Content-Type','application/octet-stream');"
"  xhr.send(f);"
"}"

/* Hardware readout + auto-refresh */
"var hwTimer=null;"
"function setHW(id,v){var e=document.getElementById(id);if(e)e.textContent=v||'N/A'}"
"function loadHW(){"
"  document.getElementById('hw-msg').innerHTML='Loading...';"
"  var x=new XMLHttpRequest();"
"  x.onload=function(){"
"    if(x.status==200){"
"      var d=JSON.parse(x.responseText);"
"      setHW('hw-fw',d.firmware);setHW('hw-chip',d.chip);"
"      setHW('hw-mac',d.mac);setHW('hw-wifi',d.wifi_mode);"
"      setHW('hw-rssi',d.wifi_rssi);setHW('hw-up',d.uptime);"
"      setHW('hw-heap',d.free_heap);setHW('hw-ctemp',d.chip_temp);"
"      setHW('hw-rst',d.reset_reason);"
"      var be=document.getElementById('hw-bench');"
"      if(be){be.childNodes[0].textContent=d.bench_mode||'N/A';}"
"      setHW('hw-dev',d.device_type);"
"      setHW('hw-btn',d.pushbutton);setHW('hw-btn2',d.switch2);"
"      setHW('hw-pcb',d.pcb_button);setHW('hw-relay',d.relay);"
"      setHW('hw-dig',d.digital_in);setHW('hw-ana',d.analog_in);"
"      setHW('hw-temp',d.temperature);setHW('hw-power',d.power);"
"      document.getElementById('hw-msg').textContent='';"
"    }else{document.getElementById('hw-msg').innerHTML='<span class=err>Read failed</span>'}"
"  };"
"  x.onerror=function(){document.getElementById('hw-msg').innerHTML='<span class=err>Connection error</span>'};"
"  x.open('GET','/api/hardware');x.send();"
"}"
"function startHWTimer(){if(!hwTimer)hwTimer=setInterval(loadHW,5000)}"
"function stopHWTimer(){if(hwTimer){clearInterval(hwTimer);hwTimer=null}}"
"function toggleBench(){"
"  if(!confirm('Toggle bench mode? Device will restart.'))return;"
"  var x=new XMLHttpRequest();"
"  x.onload=function(){"
"    if(x.status==200){document.getElementById('hw-msg').innerHTML="
"      '<span class=ok>Bench mode changed. Restarting...</span>'}"
"    else{document.getElementById('hw-msg').innerHTML="
"      '<span class=err>Failed to toggle bench mode</span>'}"
"  };"
"  x.onerror=function(){document.getElementById('hw-msg').innerHTML="
"    '<span class=err>Connection error</span>'};"
"  x.open('POST','/api/bench-mode');x.send();"
"}"
"function loadHWConfig(){"
"  var x=new XMLHttpRequest();"
"  x.onload=function(){"
"    if(x.status!=200)return;"
"    var d=JSON.parse(x.responseText);var s=document.getElementById('hw-type');"
"    s.innerHTML='';"
"    d.types.forEach(function(t){var o=document.createElement('option');"
"      o.value=t.id;o.textContent=t.name+(t.pm?' (power meter)':'');"
"      if(t.id==d.selected)o.selected=true;s.appendChild(o);});"
"  };"
"  x.open('GET','/api/hw-config');x.send();"
"}"
"function saveHWType(){"
"  var t=document.getElementById('hw-type').value;"
"  var n=document.getElementById('hw-type').selectedOptions[0].textContent;"
"  if(!confirm('Set device type to \"'+n+'\"? The device will reboot. Choosing "
"the wrong model drives the wrong GPIOs.'))return;"
"  var m=document.getElementById('hwtype-msg');"
"  var x=new XMLHttpRequest();"
"  x.onload=function(){"
"    if(x.status==200){m.innerHTML='<span class=ok>Saved. Rebooting...</span>'}"
"    else{m.innerHTML='<span class=err>Save failed</span>'}"
"  };"
"  x.onerror=function(){m.innerHTML='<span class=err>Connection error</span>'};"
"  x.open('POST','/api/hw-config');x.setRequestHeader('Content-Type','application/json');"
"  x.send(JSON.stringify({type:parseInt(t)}));"
"}"

/* Scripts */
"function loadSlot(){"
"  var s=document.getElementById('sc-slot').value;"
"  var x=new XMLHttpRequest();"
"  x.onload=function(){"
"    if(x.status==200){"
"      var d=JSON.parse(x.responseText);"
"      document.getElementById('sc-name').value=d.name||'';"
"      document.getElementById('sc-type').value=d.type||0;"
"      document.getElementById('sc-trig').value=d.trigger||0;"
"      document.getElementById('sc-period').value=d.period_ms||500;"
"      document.getElementById('sc-code').value=d.script||'';"
"      document.getElementById('sc-msg').textContent='';"
"    }else{document.getElementById('sc-msg').innerHTML='<span class=err>Load failed</span>'}"
"  };"
"  x.open('GET','/api/script?slot='+s);x.send();"
"}"

"function saveSlot(){"
"  var d={slot:parseInt(document.getElementById('sc-slot').value),"
"    name:document.getElementById('sc-name').value,"
"    type:parseInt(document.getElementById('sc-type').value),"
"    trigger:parseInt(document.getElementById('sc-trig').value),"
"    period_ms:parseInt(document.getElementById('sc-period').value),"
"    script:document.getElementById('sc-code').value};"
"  var x=new XMLHttpRequest();"
"  x.onload=function(){"
"    if(x.status==200){document.getElementById('sc-msg').innerHTML="
"      '<span class=ok>Saved! Reboot to apply endpoint changes.</span>'}"
"    else{document.getElementById('sc-msg').innerHTML="
"      '<span class=err>Error: '+x.responseText+'</span>'}"
"  };"
"  x.open('POST','/api/script');"
"  x.setRequestHeader('Content-Type','application/json');"
"  x.send(JSON.stringify(d));"
"}"

"function clearSlot(){"
"  if(!confirm('Clear this slot? Endpoint will be removed on reboot.'))return;"
"  var s=document.getElementById('sc-slot').value;"
"  var x=new XMLHttpRequest();"
"  x.onload=function(){"
"    if(x.status==200){"
"      document.getElementById('sc-name').value='';"
"      document.getElementById('sc-type').value=0;"
"      document.getElementById('sc-code').value='';"
"      document.getElementById('sc-msg').innerHTML='<span class=ok>Slot cleared</span>';"
"    }"
"  };"
"  x.open('DELETE','/api/script?slot='+s);x.send();"
"}"

"function doScriptReboot(){"
"  if(!confirm('Reboot device now?'))return;"
"  var x=new XMLHttpRequest();"
"  x.open('POST','/api/restart');x.send();"
"  document.getElementById('sc-msg').innerHTML='<span class=ok>Rebooting...</span>';"
"}"

/* Backup */
"function doBackup(){var q=document.getElementById('bk-nvs').checked?'?nvs=1':'';"
"window.location='/api/backup'+q}"

/* Restore */
"function doRestore(){"
"  var f=document.getElementById('restfile').files[0];"
"  if(!f){alert('Select a backup file first');return;}"
"  var r=new FileReader();"
"  r.onload=function(){"
"    var x=new XMLHttpRequest();"
"    x.onload=function(){"
"      if(x.status==200){document.getElementById('bk-msg').innerHTML="
"        '<span class=ok>Restored! Restarting...</span>'}"
"      else{document.getElementById('bk-msg').innerHTML="
"        '<span class=err>Error: '+x.responseText+'</span>'}"
"    };"
"    x.open('POST','/api/restore');"
"    x.setRequestHeader('Content-Type','application/json');"
"    x.send(r.result);"
"  };"
"  r.readAsText(f);"
"}"
"</script></body></html>";
