/*
 * Management dashboard HTML — auto-included by web_api.c.
 * Extracted from ota.c for maintainability.
 */
#pragma once

static const char MGMT_HTML[] =
"<!DOCTYPE html><html><head><meta charset=utf-8>"
"<meta name=viewport content='width=device-width,initial-scale=1'>"
"<title>Shelly Management</title>"
"<style>"
"*{box-sizing:border-box}body{font-family:sans-serif;max-width:560px;margin:0 auto;padding:1em}"
"h2{margin-bottom:.3em}"
".tabs{display:flex;border-bottom:2px solid #0066cc;margin:1em 0 0}"
".tab{padding:.6em 1.2em;cursor:pointer;border:1px solid #ccc;border-bottom:none;"
"  margin-right:2px;border-radius:6px 6px 0 0;background:#f5f5f5;font-size:.95em}"
".tab.act{background:#0066cc;color:#fff;border-color:#0066cc}"
".pane{display:none;padding:1em 0}.pane.act{display:block}"
"input,select{padding:.5em;margin:.3em 0 .8em;border:1px solid #ccc;border-radius:3px}"
"label{font-weight:bold;display:block;margin-top:.3em}"
".btn{padding:.55em 1.2em;color:#fff;border:0;cursor:pointer;font-size:.95em;border-radius:3px;margin:.3em .3em .3em 0}"
".btn-blue{background:#0066cc}.btn-green{background:#28a745}"
".btn-red{background:#dc3545}.btn-gray{background:#6c757d}"
".btn:disabled{background:#999;cursor:default}"
"#bar-wrap{display:none;margin:.8em 0;background:#eee;border-radius:4px;height:22px}"
"#bar{height:22px;background:#0066cc;border-radius:4px;width:0;transition:width .2s}"
"#bar-lbl{text-align:center;margin-top:.2em;font-size:.9em}"
".msg{font-weight:bold;margin-top:.6em}.ok{color:green}.err{color:red}"
"table{border-collapse:collapse;width:100%;margin:.5em 0}"
"td,th{border:1px solid #ddd;padding:6px 10px;text-align:left}"
"th{background:#f0f0f0}.hw-val{font-family:monospace;font-size:1.1em}"
"h4{margin:1.2em 0 .3em;color:#333;border-bottom:1px solid #ddd;padding-bottom:.2em}"
".info{font-size:.85em;color:#555;margin-bottom:.8em}"
"</style></head><body>"

"<h2 id=page-title>Shelly1Gen4 Management</h2>"
"<div id=fw-ver style='font-size:.85em;color:#666;margin-bottom:.5em'></div>"

/* ── Tab bar ── */
"<div class=tabs>"
"<div class='tab act' onclick=showTab(0)>WiFi &amp; OTA</div>"
"<div class=tab onclick=showTab(1)>Hardware</div>"
"<div class=tab onclick=showTab(2)>Scripts</div>"
"<div class=tab onclick=showTab(3)>Backup</div>"
"<div class=tab onclick=showTab(4)>Log</div>"
"</div>"

/* ── Tab 0: WiFi & OTA ── */
"<div class='pane act' id=p0>"
"<h3>WiFi Settings</h3>"
"<p class=info>Credentials are stored in flash and used by the temporary WiFi "
"window. <b>Apply</b> only saves them — no reboot: toggle the window below to "
"connect with the new settings, so a wrong SSID costs a toggle instead of a "
"restart.</p>"
"<p class=info><b>WiFi</b> joins WiFi (station only) next to a running Thread "
"network, without a reboot. <b>10 min</b> switches WiFi off again after 10 "
"minutes (6&times; press on any input does the same, and extends the window); "
"<b>Always on</b> keeps it up and restores it after a reboot; <b>Off</b> "
"closes it. WiFi and Thread share one radio, so while WiFi is on the device "
"gives up its Thread router role and its SRP fallback server and Thread "
"traffic is slower; both come back when WiFi goes off. The 10-minute window "
"may pause the Lua scripts to free heap for the WiFi driver; Always on never "
"does, so it needs enough free heap next to the configured slots.</p>"
"<label>Hostname</label><input id=hostname placeholder='shelly-XXXXXX' maxlength=31>"
"<label>WiFi SSID</label><input id=ssid>"
"<label>WiFi Password</label><input id=pass type=password>"
"<label>Firmware URL (optional)</label>"
"<input id=url placeholder='http://server/shelly1gen4.bin'>"
"<div style='margin:1em 0'>"
"<button class='btn btn-green' onclick=doApply()>Apply</button>"
"<button class='btn btn-blue' onclick=doCommission()>Commission Mode</button>"
"<button class='btn btn-gray' onclick=doRestart()>Restart</button>"
"<button class='btn btn-red' onclick=doFactory()>Factory Reset</button>"
"</div>"
"<div style='margin:0 0 1em'><b>WiFi next to Thread:</b> "
"<button class='btn btn-gray' onclick=doWifiCoex('off')>Off</button>"
"<button class='btn btn-blue' onclick=doWifiCoex('temp')>10 min</button>"
"<button class='btn btn-blue' onclick=doWifiCoex('always')>Always on</button>"
"</div>"
"<div id=wifi-msg class=msg></div>"

"<h3>Upload Firmware</h3>"
"<p class=info>Or fetch the firmware URL above directly — that needs a route to "
"the server, so open the WiFi window first unless it is reachable over Thread. "
"<button class='btn btn-blue' onclick=doOtaUrl()>Update from URL</button></p>"
"<label for=binfile>Select .bin file</label>"
"<input type=file id=binfile accept='.bin'>"
"<button class='btn btn-blue' id=flashbtn onclick=doUpload()>Flash Firmware</button>"
"<div id=bar-wrap><div id=bar></div></div>"
"<div id=bar-lbl></div>"
"<div id=flash-msg class=msg></div>"
"</div>"

/* ── Tab 1: Hardware ── */
"<div class=pane id=p1>"
"<h3>Hardware Status</h3>"
"<p class=info>Live readings (auto-refresh every 5 s). "
"<button class='btn btn-blue' onclick=loadHW()>Refresh now</button></p>"

"<h4>Device Type</h4>"
"<p class=info>Select the Shelly model this firmware runs on. This sets the "
"relay/switch/button/LED GPIOs and enables the power meter on the 1PM. "
"<b>Warning:</b> choosing the wrong model drives the wrong GPIOs. Saving "
"reboots the device. Matter re-commissioning is <b>not</b> required.</p>"
"<label>Model</label>"
"<select id=hw-type></select>"
"<div style='margin:.6em 0'>"
"<button class='btn btn-blue' onclick=saveHWType()>Save &amp; reboot</button>"
"</div>"
"<div id=hwtype-msg class=msg></div>"

"<h4>System</h4>"
"<table><tr><th style='width:45%'>Item</th><th>Value</th></tr>"
"<tr><td>Firmware</td><td class=hw-val id=hw-fw>-</td></tr>"
"<tr><td>Active device type</td><td class=hw-val id=hw-dev>-</td></tr>"
"<tr><td>Chip</td><td class=hw-val id=hw-chip>-</td></tr>"
"<tr><td>MAC address</td><td class=hw-val id=hw-mac>-</td></tr>"
"<tr><td>WiFi mode</td><td class=hw-val id=hw-wifi>-</td></tr>"
"<tr><td>WiFi RSSI</td><td class=hw-val id=hw-rssi>-</td></tr>"
"<tr><td>Uptime</td><td class=hw-val id=hw-up>-</td></tr>"
"<tr><td>Free heap</td><td class=hw-val id=hw-heap>-</td></tr>"
"<tr><td>Chip temperature</td><td class=hw-val id=hw-ctemp>-</td></tr>"
"<tr><td>Reset reason</td><td class=hw-val id=hw-rst>-</td></tr>"
"<tr><td>Bench mode<br><span style='font-size:.8em;color:#666'>"
"ON = GPIO10 pull-up, sensor tasks skipped (UART0 stays active).<br>"
"OFF = production (230V optocoupler, DS18B20 + occupancy running).</span></td>"
"<td class=hw-val id=hw-bench>-<br>"
"<button class='btn btn-gray' id=bench-btn onclick=toggleBench() style='margin-top:.4em'>Toggle</button>"
"</td></tr>"
"<tr><td>WiFi next to Thread<br><span style='font-size:.8em;color:#666'>"
"WiFi station next to Thread, no reboot: off, 10 minutes, or always on. "
"Thread router role and SRP fallback stand down while WiFi is on.</span></td>"
"<td class=hw-val id=hw-wtemp>-<br>"
"<button class='btn btn-gray' onclick=doWifiCoex('off') style='margin-top:.4em'>Off</button>"
"<button class='btn btn-gray' onclick=doWifiCoex('temp') style='margin-top:.4em'>10 min</button>"
"<button class='btn btn-gray' onclick=doWifiCoex('always') style='margin-top:.4em'>Always on</button>"
"</td></tr>"
"<tr><td>SRP fallback server<br><span style='font-size:.8em;color:#666'>"
"Runs a Thread SRP/DNS-SD server only while no border router is present, so "
"local bindings keep resolving during a TBR outage. Yields immediately to a "
"real border router. Toggling reboots the device.</span></td>"
"<td class=hw-val id=hw-srp>-<br>"
"<button class='btn btn-gray' onclick=toggleSrp() style='margin-top:.4em'>Toggle</button>"
"</td></tr>"
"<tr><td>Binding keepalive<br><span style='font-size:.8em;color:#666'>"
"Interval in seconds for the reachability check on bound devices. Detects a "
"stale cached address in the background, so the first press after a network "
"change is not delayed. 0 = off, minimum 60.</span></td>"
"<td class=hw-val>"
"<input id=hw-ka type=number min=0 max=86400 style='width:6em'> s<br>"
"<button class='btn btn-gray' onclick=saveKeepalive() style='margin-top:.4em'>Save</button>"
"</td></tr>"

"</table>"

"<h4>Inputs</h4>"
"<table><tr><th style='width:45%'>Input</th><th>Value</th></tr>"
"<tr><td>Wall switch</td><td class=hw-val id=hw-btn>-</td></tr>"
"<tr><td>Wall switch 2 (2PM)</td><td class=hw-val id=hw-btn2>-</td></tr>"
"<tr><td>PCB button</td><td class=hw-val id=hw-pcb>-</td></tr>"
"<tr><td>Digital IN (Add-on)</td><td class=hw-val id=hw-dig>-</td></tr>"
"<tr><td>Analog IN (Add-on)</td><td class=hw-val id=hw-ana>-</td></tr>"
"</table>"

"<h4>Outputs</h4>"
"<table><tr><th style='width:45%'>Output</th><th>Value</th></tr>"
"<tr><td>Relay</td><td class=hw-val id=hw-relay>-</td></tr>"
"</table>"

"<h4>Sensors</h4>"
"<table><tr><th style='width:45%'>Sensor</th><th>Value</th></tr>"
"<tr><td>Temperature (DS18B20)</td><td class=hw-val id=hw-temp>-</td></tr>"
"<tr><td>Power meter</td><td class=hw-val id=hw-power>-</td></tr>"
"</table>"

"<p><button class='btn btn-blue' onclick=runOwProbe()>Diagnose 1-Wire</button>"
"<span class=info> drives the Add-on bus for about a second and reports what the pins do</span></p>"
"<pre id=ow-out style='display:none;font-size:.8em;white-space:pre-wrap;"
"border:1px solid #ccc;border-radius:3px;padding:.5em'></pre>"
"<div id=hw-msg class=msg></div>"
"</div>"

/* ── Tab 2: Scripts ── */
"<div class=pane id=p2>"
"<h3>Endpoint Scripts</h3>"
"<p class=info>Configure Matter endpoints via Lua scripts. Each slot is one endpoint. "
"Changes require a reboot to recreate endpoints.</p>"

"<label>Slot</label>"
"<select id=sc-slot onchange=loadSlot()>"
"<option value=0>Slot 0</option><option value=1>Slot 1</option>"
"<option value=2>Slot 2</option><option value=3>Slot 3</option>"
"<option value=4>Slot 4</option><option value=5>Slot 5</option>"
"<option value=6>Slot 6</option><option value=7>Slot 7</option>"
"</select>"

"<label>Name</label><input id=sc-name placeholder='e.g. Pushbutton Toggle'>"

"<label>Endpoint Type</label>"
"<select id=sc-type>"
"<option value=0>None (disabled)</option>"
"<option value=1>OnOff Toggle + Dim + Color (client)</option>"
"<option value=2>OnOff State-Follow (client)</option>"
"<option value=4>Occupancy Sensor</option>"
"<option value=5>Illuminance Sensor</option>"
"<option value=6>Temperature Sensor</option>"
"<option value=7>Relay (OnOff Light server)</option>"
"<option value=8>Relay 2 (OnOff Light server, 2PM)</option>"
"<option value=9>Contact Sensor (BooleanState server)</option>"
"<option value=10>Electrical Power Measurement (server)</option>"
"</select>"

"<label>Trigger</label>"
"<select id=sc-trig>"
"<option value=0>Periodic</option>"
"<option value=1>On input change</option>"
"<option value=2>On button event</option>"
"</select>"

"<label>Period (ms, for periodic trigger)</label>"
"<input id=sc-period type=number value=500 min=50 max=60000>"

"<label>Lua Script</label>"
"<textarea id=sc-code style='width:100%;height:200px;font-family:monospace;font-size:.9em;"
"  tab-size:2;white-space:pre;border:1px solid #ccc;border-radius:3px;padding:.5em'"
"  placeholder='-- Write your Lua script here&#10;function run()&#10;  local evt = input.button_event()&#10;  if evt == \"short_press\" then&#10;    endpoint.command(\"toggle\")&#10;  end&#10;end'></textarea>"

"<div style='margin:1em 0'>"
"<button class='btn btn-green' onclick=saveSlot()>Save Slot</button>"
"<button class='btn btn-red' onclick=clearSlot()>Clear Slot</button>"
"<button class='btn btn-gray' onclick=loadSlot()>Reload</button>"
"</div>"
"<div id=sc-msg class=msg></div>"
"<hr style='margin:1.5em 0'>"
"<button class='btn btn-red' onclick=doScriptReboot()>Reboot Device</button>"
"<p class=info>Reboot to apply endpoint type changes.</p>"
"</div>"

/* ── Tab 3: Backup / Restore ── */
"<div class=pane id=p3>"
"<h3>Backup &amp; Restore</h3>"
"<p class=info>Download all saved settings as a backup file, or restore "
"from a previously saved backup.</p>"
"<div style='margin:.8em 0'>"
"<label style='font-weight:normal;cursor:pointer'>"
"<input type=checkbox id=bk-nvs style='margin-right:.4em;vertical-align:middle'>"
"Include NVS (Matter commissioning data)</label></div>"
"<button class='btn btn-blue' onclick=doBackup()>Download Backup</button>"
"<h3>Restore from file</h3>"
"<input type=file id=restfile accept='.json'>"
"<button class='btn btn-green' onclick=doRestore()>Restore Backup</button>"
"<div id=bk-msg class=msg></div>"

"<h3>Return to stock Shelly firmware</h3>"
"<p class=info>Upload an original Shelly firmware package (the <b>.zip</b> the "
"stock web UI uses) to go back to stock. It writes the stock app + filesystem "
"and points the boot loader back at stock. The bootloader and the factory "
"<code>shelly</code> partition (Matter/hardware credentials) are never touched. "
"Only works on units installed via the web-UI package (stock loader preserved).</p>"
"<p class=info><b>Warning:</b> flashing is at your own risk and this path is "
"<b>not hardware-tested</b>. Keep a full UART backup as your guaranteed way "
"back. Pick the package that matches the model on your device label "
"(e.g. <code>S4SW-001X16EU</code> = Shelly 1 Gen4).</p>"
"<p class=info>Find the official stock firmware for this exact module "
"(model read from the factory partition):</p>"
"<button class='btn btn-blue' id=stockfindbtn onclick=findStockFw()>"
"Find latest stock firmware</button>"
"<div id=stockfw-msg class=msg></div>"
"<input type=file id=stockfile accept='.zip'>"
"<button class='btn btn-red' id=stockbtn onclick=doRestoreStock()>"
"Flash stock firmware</button>"
"<div id=stock-bar-wrap style='display:none'><div id=stock-bar></div></div>"
"<div id=stock-bar-lbl></div>"
"<div id=stock-msg class=msg></div>"
"</div>"

/* ── Tab 4: Log ── */
"<div class=pane id=p4>"
"<h3>Device Log</h3>"
"<p class=info>Last 8 kB of ESP_LOG output, kept in RAM. Useful when the Add-on "
"occupies GPIO16/17 and no serial console is available.</p>"
"<p><label><input type=checkbox id=log-auto checked> Auto-refresh (5 s)</label> "
"<button class='btn btn-blue' onclick=loadLog()>Refresh now</button></p>"
"<pre id=log-txt style='max-height:60vh;overflow:auto;font-size:.8em;"
"  white-space:pre-wrap;border:1px solid #ccc;border-radius:3px;padding:.5em'></pre>"
"</div>"

"<script>"
/* Tab switching */
"function showTab(n){"
"  document.querySelectorAll('.tab').forEach(function(t,i){t.className=i==n?'tab act':'tab'});"
"  document.querySelectorAll('.pane').forEach(function(p,i){p.className=i==n?'pane act':'pane'});"
"  if(n==1){loadHWConfig();loadHW();startHWTimer()}else{stopHWTimer()}"
"  if(n==2){loadSlot()}"
"  if(n==4){loadLog();startLogTimer()}else{stopLogTimer()}"
"}"

/* Device log readout + auto-refresh */
"var logTimer=null;"
"function loadLog(){"
"  var x=new XMLHttpRequest();"
"  x.onload=function(){"
"    if(x.status==200){"
"      var e=document.getElementById('log-txt');"
"      var atEnd=e.scrollTop+e.clientHeight>=e.scrollHeight-20;"
"      e.textContent=x.responseText;"
"      if(atEnd)e.scrollTop=e.scrollHeight;"
"    }"
"  };"
"  x.open('GET','/api/log');x.send();"
"}"
"function startLogTimer(){"
"  if(!logTimer)logTimer=setInterval(function(){"
"    if(document.getElementById('log-auto').checked)loadLog();"
"  },5000);"
"}"
"function stopLogTimer(){if(logTimer){clearInterval(logTimer);logTimer=null}}"

/* Load saved settings + firmware version on page load */
"function loadSettings(){"
"  var x=new XMLHttpRequest();"
"  x.onload=function(){"
"    if(x.status==200){"
"      var d=JSON.parse(x.responseText);"
"      document.getElementById('hostname').value=d.hostname||'';"
"      document.getElementById('ssid').value=d.ssid||'';"
"      document.getElementById('pass').value=d.pass||'';"
"      document.getElementById('url').value=d.url||'';"
"      if(d.version){document.getElementById('fw-ver').textContent='Firmware: '+d.version}"
"      if(d.hostname){document.getElementById('page-title').textContent=d.hostname+' Management';document.title=d.hostname+' Management'}"
"    }"
"  };"
"  x.open('GET','/api/settings');x.send();"
"}"
"loadSettings();"

/* WiFi settings: store only, no reboot */
"function doApply(){"
"  var b='hostname='+encodeURIComponent(document.getElementById('hostname').value)"
"    +'&ssid='+encodeURIComponent(document.getElementById('ssid').value)"
"    +'&pass='+encodeURIComponent(document.getElementById('pass').value)"
"    +'&url='+encodeURIComponent(document.getElementById('url').value);"
"  var x=new XMLHttpRequest();"
"  x.onload=function(){document.getElementById('wifi-msg').innerHTML="
"    (x.status==200?'<span class=ok>':'<span class=err>')+x.responseText+'</span>'};"
"  x.onerror=function(){document.getElementById('wifi-msg').innerHTML="
"    '<span class=err>Connection error</span>'};"
"  x.open('POST','/ota');x.setRequestHeader('Content-Type','application/x-www-form-urlencoded');"
"  x.send(b);"
"}"

/* Plain reboot */
"function doRestart(){"
"  if(!confirm('Restart the device now?'))return;"
"  var x=new XMLHttpRequest();"
"  x.onload=function(){document.getElementById('wifi-msg').innerHTML="
"    '<span class=ok>Restarting...</span>'};"
"  x.onerror=function(){document.getElementById('wifi-msg').innerHTML="
"    '<span class=ok>Restarting...</span>'};"
"  x.open('POST','/api/restart');x.send();"
"}"

/* Fetch the saved firmware URL */
"function doOtaUrl(){"
"  if(!confirm('Fetch the firmware URL now? The device reboots into it when it succeeds.'))return;"
"  var x=new XMLHttpRequest();"
"  x.onload=function(){document.getElementById('flash-msg').innerHTML="
"    (x.status==200?'<span class=ok>':'<span class=err>')+x.responseText+'</span>'};"
"  x.onerror=function(){document.getElementById('flash-msg').innerHTML="
"    '<span class=err>Connection error</span>'};"
"  x.open('POST','/api/ota-url');x.send();"
"}"

/* WiFi next to Thread (no reboot): mode = off | temp | always */
"function doWifiCoex(m){"
"  var x=new XMLHttpRequest();"
"  x.onload=function(){document.getElementById('wifi-msg').innerHTML="
"    (x.status==200?'<span class=ok>':'<span class=err>')+x.responseText+'</span>';"
"    if(typeof loadHW=='function')loadHW();};"
"  x.onerror=function(){document.getElementById('wifi-msg').innerHTML="
"    '<span class=err>Connection error</span>'};"
"  x.open('POST','/api/wifi-coex?mode='+m);x.send();"
"}"

/* Commission mode */
"function doCommission(){"
"  if(!confirm('Commission Mode: removes all Matter pairings and reboots into BLE pairing mode. WiFi and script settings are kept. Continue?'))return;"
"  var x=new XMLHttpRequest();"
"  x.onload=function(){document.getElementById('wifi-msg').innerHTML="
"    '<span class=ok>Rebooting into commission mode...</span>'};"
"  x.open('POST','/api/commission');x.send();"
"}"

/* Factory reset */
"function doFactory(){"
"  if(!confirm('WARNING: This erases ALL settings and Matter pairing data. Continue?'))return;"
"  if(!confirm('Are you really sure? This cannot be undone!'))return;"
"  var x=new XMLHttpRequest();"
"  x.onload=function(){document.getElementById('wifi-msg').innerHTML="
"    '<span class=ok>Factory reset done. Restarting...</span>'};"
"  x.open('POST','/api/factory-reset');x.send();"
"}"

/* Firmware upload */
"function doUpload(){"
"  var f=document.getElementById('binfile').files[0];"
"  if(!f){alert('Select a .bin file first');return;}"
"  var btn=document.getElementById('flashbtn');"
"  var wrap=document.getElementById('bar-wrap');"
"  var bar=document.getElementById('bar');"
"  var lbl=document.getElementById('bar-lbl');"
"  var st=document.getElementById('flash-msg');"
"  btn.disabled=true;wrap.style.display='block';st.textContent='';st.className='msg';"
"  var xhr=new XMLHttpRequest();"
"  xhr.upload.onprogress=function(e){"
"    if(e.lengthComputable){"
"      var pct=Math.round(e.loaded/e.total*100);"
"      bar.style.width=pct+'%';"
"      lbl.textContent='Uploading: '+pct+'% ('+Math.round(e.loaded/1024)+'/'+"
"        Math.round(e.total/1024)+' KB)';"
"    }"
"  };"
"  xhr.onload=function(){"
"    if(xhr.status===200){"
"      bar.style.width='100%';"
"      lbl.textContent='Upload complete';"
"      st.innerHTML='<span class=ok>Flashed! Restarting...</span>';"
"    }else{"
"      st.innerHTML='<span class=err>Error: '+xhr.responseText+'</span>';"
"      btn.disabled=false;"
"    }"
"  };"
"  xhr.onerror=function(){"
"    st.innerHTML='<span class=err>Connection lost</span>';btn.disabled=false;};"
"  xhr.open('POST','/upload');"
"  xhr.setRequestHeader('Content-Type','application/octet-stream');"
"  xhr.send(f);"
"}"

/* Hardware readout + auto-refresh */
"var hwTimer=null;"
"function setHW(id,v){var e=document.getElementById(id);if(e)e.textContent=v||'N/A'}"
"function loadHW(){"
"  document.getElementById('hw-msg').innerHTML='Loading...';"
"  var x=new XMLHttpRequest();"
"  x.onload=function(){"
"    if(x.status==200){"
"      var d=JSON.parse(x.responseText);"
"      setHW('hw-fw',d.firmware);setHW('hw-chip',d.chip);"
"      setHW('hw-mac',d.mac);setHW('hw-wifi',d.wifi_mode);"
"      setHW('hw-rssi',d.wifi_rssi);setHW('hw-up',d.uptime);"
"      setHW('hw-heap',d.free_heap);setHW('hw-ctemp',d.chip_temp);"
"      setHW('hw-rst',d.reset_reason);"
"      var be=document.getElementById('hw-bench');"
"      if(be){be.childNodes[0].textContent=d.bench_mode||'N/A';}"
"      var we=document.getElementById('hw-wtemp');"
"      if(we){we.childNodes[0].textContent=d.wifi_temp||'N/A';}"
"      var se=document.getElementById('hw-srp');"
"      if(se){se.childNodes[0].textContent=d.srp_mode||'N/A';}"
"      setHW('hw-dev',d.device_type);"
"      setHW('hw-btn',d.pushbutton);setHW('hw-btn2',d.switch2);"
"      setHW('hw-pcb',d.pcb_button);setHW('hw-relay',d.relay);"
"      setHW('hw-dig',d.digital_in);setHW('hw-ana',d.analog_in);"
"      setHW('hw-temp',d.temperature);setHW('hw-power',d.power);"
"      var ka=document.getElementById('hw-ka');"
"      if(ka&&ka!==document.activeElement)ka.value=d.keepalive_s;"
"      document.getElementById('hw-msg').textContent='';"
"    }else{document.getElementById('hw-msg').innerHTML='<span class=err>Read failed</span>'}"
"  };"
"  x.onerror=function(){document.getElementById('hw-msg').innerHTML='<span class=err>Connection error</span>'};"
"  x.open('GET','/api/hardware');x.send();"
"}"
"function runOwProbe(){"
"  var e=document.getElementById('ow-out');"
"  e.style.display='block';e.textContent='probing...';"
"  var x=new XMLHttpRequest();"
"  x.onload=function(){e.textContent=x.responseText};"
"  x.onerror=function(){e.textContent='probe request failed'};"
"  x.open('GET','/api/owprobe');x.send();"
"}"

"function startHWTimer(){if(!hwTimer)hwTimer=setInterval(loadHW,5000)}"
"function stopHWTimer(){if(hwTimer){clearInterval(hwTimer);hwTimer=null}}"
"function toggleBench(){"
"  if(!confirm('Toggle bench mode? Device will restart.'))return;"
"  var x=new XMLHttpRequest();"
"  x.onload=function(){"
"    if(x.status==200){document.getElementById('hw-msg').innerHTML="
"      '<span class=ok>Bench mode changed. Restarting...</span>'}"
"    else{document.getElementById('hw-msg').innerHTML="
"      '<span class=err>Failed to toggle bench mode</span>'}"
"  };"
"  x.onerror=function(){document.getElementById('hw-msg').innerHTML="
"    '<span class=err>Connection error</span>'};"
"  x.open('POST','/api/bench-mode');x.send();"
"}"
"function toggleSrp(){"
"  if(!confirm('Toggle the SRP fallback server? Device will restart.'))return;"
"  var x=new XMLHttpRequest();"
"  x.onload=function(){"
"    if(x.status==200){document.getElementById('hw-msg').innerHTML="
"      '<span class=ok>SRP fallback changed. Restarting...</span>'}"
"    else{document.getElementById('hw-msg').innerHTML="
"      '<span class=err>Failed to toggle the SRP fallback</span>'}"
"  };"
"  x.onerror=function(){document.getElementById('hw-msg').innerHTML="
"    '<span class=err>Connection error</span>'};"
"  x.open('POST','/api/srp-mode');x.send();"
"}"
"function saveKeepalive(){"
"  var v=parseInt(document.getElementById('hw-ka').value,10);"
"  if(isNaN(v)||(v!=0&&(v<60||v>86400))){document.getElementById('hw-msg').innerHTML="
"    '<span class=err>Use 0 to disable, otherwise 60..86400 s</span>';return}"
"  var x=new XMLHttpRequest();"
"  x.onload=function(){"
"    if(x.status==200){document.getElementById('hw-msg').innerHTML="
"      '<span class=ok>Keepalive interval saved</span>'}"
"    else{document.getElementById('hw-msg').innerHTML="
"      '<span class=err>Failed to save keepalive interval</span>'}"
"  };"
"  x.onerror=function(){document.getElementById('hw-msg').innerHTML="
"    '<span class=err>Connection error</span>'};"
"  x.open('POST','/api/keepalive');"
"  x.setRequestHeader('Content-Type','application/json');"
"  x.send(JSON.stringify({seconds:v}));"
"}"
"function loadHWConfig(){"
"  var x=new XMLHttpRequest();"
"  x.onload=function(){"
"    if(x.status!=200)return;"
"    var d=JSON.parse(x.responseText);var s=document.getElementById('hw-type');"
"    s.innerHTML='';"
"    d.types.forEach(function(t){var o=document.createElement('option');"
"      o.value=t.id;o.textContent=t.name+(t.pm?' (power meter)':'');"
"      if(t.id==d.selected)o.selected=true;s.appendChild(o);});"
"  };"
"  x.open('GET','/api/hw-config');x.send();"
"}"
"function saveHWType(){"
"  var t=document.getElementById('hw-type').value;"
"  var n=document.getElementById('hw-type').selectedOptions[0].textContent;"
"  if(!confirm('Set device type to \"'+n+'\"? The device will reboot. Choosing "
"the wrong model drives the wrong GPIOs.'))return;"
"  var m=document.getElementById('hwtype-msg');"
"  var x=new XMLHttpRequest();"
"  x.onload=function(){"
"    if(x.status==200){m.innerHTML='<span class=ok>Saved. Rebooting...</span>'}"
"    else{m.innerHTML='<span class=err>Save failed</span>'}"
"  };"
"  x.onerror=function(){m.innerHTML='<span class=err>Connection error</span>'};"
"  x.open('POST','/api/hw-config');x.setRequestHeader('Content-Type','application/json');"
"  x.send(JSON.stringify({type:parseInt(t)}));"
"}"

/* Scripts */
"function loadSlot(){"
"  var s=document.getElementById('sc-slot').value;"
"  var x=new XMLHttpRequest();"
"  x.onload=function(){"
"    if(x.status==200){"
"      var d=JSON.parse(x.responseText);"
"      document.getElementById('sc-name').value=d.name||'';"
"      document.getElementById('sc-type').value=d.type||0;"
"      document.getElementById('sc-trig').value=d.trigger||0;"
"      document.getElementById('sc-period').value=d.period_ms||500;"
"      document.getElementById('sc-code').value=d.script||'';"
"      document.getElementById('sc-msg').textContent='';"
"    }else{document.getElementById('sc-msg').innerHTML='<span class=err>Load failed</span>'}"
"  };"
"  x.open('GET','/api/script?slot='+s);x.send();"
"}"

"function saveSlot(){"
"  var d={slot:parseInt(document.getElementById('sc-slot').value),"
"    name:document.getElementById('sc-name').value,"
"    type:parseInt(document.getElementById('sc-type').value),"
"    trigger:parseInt(document.getElementById('sc-trig').value),"
"    period_ms:parseInt(document.getElementById('sc-period').value),"
"    script:document.getElementById('sc-code').value};"
"  var x=new XMLHttpRequest();"
"  x.onload=function(){"
"    if(x.status==200){document.getElementById('sc-msg').innerHTML="
"      '<span class=ok>Saved! Reboot to apply endpoint changes.</span>'}"
"    else{document.getElementById('sc-msg').innerHTML="
"      '<span class=err>Error: '+x.responseText+'</span>'}"
"  };"
"  x.open('POST','/api/script');"
"  x.setRequestHeader('Content-Type','application/json');"
"  x.send(JSON.stringify(d));"
"}"

"function clearSlot(){"
"  if(!confirm('Clear this slot? Endpoint will be removed on reboot.'))return;"
"  var s=document.getElementById('sc-slot').value;"
"  var x=new XMLHttpRequest();"
"  x.onload=function(){"
"    if(x.status==200){"
"      document.getElementById('sc-name').value='';"
"      document.getElementById('sc-type').value=0;"
"      document.getElementById('sc-code').value='';"
"      document.getElementById('sc-msg').innerHTML='<span class=ok>Slot cleared</span>';"
"    }"
"  };"
"  x.open('DELETE','/api/script?slot='+s);x.send();"
"}"

"function doScriptReboot(){"
"  if(!confirm('Reboot device now?'))return;"
"  var x=new XMLHttpRequest();"
"  x.open('POST','/api/restart');x.send();"
"  document.getElementById('sc-msg').innerHTML='<span class=ok>Rebooting...</span>';"
"}"

/* Backup */
"function doBackup(){var q=document.getElementById('bk-nvs').checked?'?nvs=1':'';"
"window.location='/api/backup'+q}"

/* Restore */
"function doRestore(){"
"  var f=document.getElementById('restfile').files[0];"
"  if(!f){alert('Select a backup file first');return;}"
"  var r=new FileReader();"
"  r.onload=function(){"
"    var x=new XMLHttpRequest();"
"    x.onload=function(){"
"      if(x.status==200){document.getElementById('bk-msg').innerHTML="
"        '<span class=ok>Restored! Restarting...</span>'}"
"      else{document.getElementById('bk-msg').innerHTML="
"        '<span class=err>Error: '+x.responseText+'</span>'}"
"    };"
"    x.open('POST','/api/restore');"
"    x.setRequestHeader('Content-Type','application/json');"
"    x.send(r.result);"
"  };"
"  r.readAsText(f);"
"}"

/* Resolve latest stock firmware via the device (reads model from factory partition) */
"function findStockFw(){"
"  var b=document.getElementById('stockfindbtn');"
"  var m=document.getElementById('stockfw-msg');"
"  b.disabled=true;m.className='msg';m.textContent='Looking up latest stock firmware...';"
"  fetch('/api/stock-fw').then(function(r){return r.json();}).then(function(d){"
"    b.disabled=false;"
"    if(d.ok){m.innerHTML='<span class=ok>'+(d.model||'')+' &rarr; '+(d.app||'')+"
"      ' stable '+d.version+':</span> <a href=\"'+d.url+'\" target=_blank rel=noopener>"
"Download stock firmware .zip</a>';}"
"    else{m.innerHTML='<span class=err>'+(d.error||'lookup failed')+"
"      (d.model?(' (model '+d.model+')'):'')+'</span>';}"
"  }).catch(function(){b.disabled=false;"
"    m.innerHTML='<span class=err>Request failed (device may be offline)</span>';});"
"}"

/* Return to stock */
"function doRestoreStock(){"
"  var f=document.getElementById('stockfile').files[0];"
"  if(!f){alert('Select a stock firmware .zip first');return;}"
"  if(!confirm('Flash STOCK Shelly firmware? This replaces the custom firmware. "
"Make sure you have a full UART backup.'))return;"
"  var btn=document.getElementById('stockbtn');"
"  var wrap=document.getElementById('stock-bar-wrap');"
"  var bar=document.getElementById('stock-bar');"
"  var lbl=document.getElementById('stock-bar-lbl');"
"  var st=document.getElementById('stock-msg');"
"  btn.disabled=true;wrap.style.display='block';st.textContent='';st.className='msg';"
"  var xhr=new XMLHttpRequest();"
"  xhr.upload.onprogress=function(e){"
"    if(e.lengthComputable){var pct=Math.round(e.loaded/e.total*100);"
"      bar.style.width=pct+'%';lbl.textContent='Uploading: '+pct+'%';}"
"  };"
"  xhr.onload=function(){"
"    if(xhr.status===200){bar.style.width='100%';"
"      st.innerHTML='<span class=ok>Stock firmware flashed! Restarting into stock...</span>';}"
"    else{st.innerHTML='<span class=err>Error: '+xhr.responseText+'</span>';btn.disabled=false;}"
"  };"
"  xhr.onerror=function(){"
"    st.innerHTML='<span class=err>Connection lost</span>';btn.disabled=false;};"
"  xhr.open('POST','/api/restore-stock');"
"  xhr.setRequestHeader('Content-Type','application/octet-stream');"
"  xhr.send(f);"
"}"
"</script></body></html>";
