# Generate a C source embedding the freshly built ESP-IDF bootloader image.
#
# Run at build time (not configure time) so build/bootloader/bootloader.bin
# already exists. Emits idf_bootloader_bin[] + idf_bootloader_bin_len, which
# loader_migrate.c writes to flash offset 0x0 during the one-time stock->ESP-IDF
# loader migration.
#
# Invoked as: cmake -DINPUT=<bin> -DOUTPUT=<c> -P embed_bootloader.cmake

file(READ "${INPUT}" hex HEX)
string(LENGTH "${hex}" hexlen)
math(EXPR count "${hexlen} / 2")
string(REGEX REPLACE "(..)" "0x\\1," bytes "${hex}")

file(WRITE "${OUTPUT}"
"/* Generated by embed_bootloader.cmake -- do not edit. */\n"
"#include <stddef.h>\n"
"const unsigned char idf_bootloader_bin[] = { ${bytes} };\n"
"const size_t idf_bootloader_bin_len = ${count};\n")
